<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>rOpenSci | osmplotr tutorial</title>

     
    <script src="//cdn.bootcss.com/highlight.js/9.12.0/highlight.min.js"></script>
    <script src="//cdn.bootcss.com/highlight.js/9.12.0/languages/r.min.js"></script>

    <script type="text/javascript">
    hljs.configure({languages: []});
    hljs.initHighlightingOnLoad();
    </script>
    <link rel="stylesheet" type="text/css" href="/css/style-new.css" />
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#4b8add">
<meta name="theme-color" content="#4b8add">


    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

    
    <div id="header">
        <div class="container">
            <div class="row center-m">
                
                <div class="col-1">
                    <a href="/index.html"><img src="/img/icon_lettering_white.svg" /></a>
                </div>
                
                
                <nav class="col-6 col-offset-4 top-3">
                    <ul class="row between">
						<li><a href="/about/">About</a></li>
                        <li><a href="/blog/">Blog</a></li>
                        <li><a href="/packages/">Packages</a></li>
                        <li><a href="/community/">Community</a></li>
                        <li><a href="http://discuss.ropensci.org/" target="_blank">Discuss</a></li>

                    </ul>
                </nav>
                
            </div>
        </div>
    </div>



    <article>
        <div class="container top-20">
            
            <div class="row centered">
                
                <div class="col-7 bottom-20 maintext">
                    <h1>osmplotr tutorial</h1>
                    <br>
                    <h4><small style="color:grey">for v0.3.0</small></h4>
                    <br>

                    <article>
                    

<h3 id="installation">Installation</h3>

<p>Stable version from CRAN</p>

<pre><code class="language-r">install.packages(&quot;osmplotr&quot;)
</code></pre>

<p>Development version from GitHub</p>

<pre><code class="language-r">if (!require(&quot;devtools&quot;)) install.packages(&quot;devtools&quot;)
devtools::install_github(&quot;ropenscilabs/osmplotr&quot;)
</code></pre>

<pre><code class="language-r">library(&quot;osmplotr&quot;)
library(&quot;maptools&quot;)
</code></pre>

<h2 id="usage">Usage</h2>

<h3 id="introduction">Introduction</h3>

<p>A map can be generated using the following simple steps:</p>

<ol>
<li>Specify the bounding box for the desired region</li>
</ol>

<pre><code class="language-r">bbox &lt;- get_bbox(c (-0.13, 51.51, -0.11, 51.52))
</code></pre>

<ol>
<li>Download the desired data&mdash;in this case, all building perimeters.</li>
</ol>

<pre><code class="language-r">dat_B &lt;- extract_osm_objects(key='building', bbox=bbox)
</code></pre>

<ol>
<li>Initiate an <code>osm_basemap</code> with desired background (<code>bg</code>) colour</li>
</ol>

<pre><code class="language-r">map &lt;- osm_basemap(bbox = bbox, bg = 'gray20')
</code></pre>

<ol>
<li>Add desired plotting objects in the desired colour.</li>
</ol>

<pre><code class="language-r">map &lt;- add_osm_objects(map, dat_B, col = 'gray40')
</code></pre>

<ol>
<li>Print the map</li>
</ol>

<pre><code class="language-r">print_osm_map(map)
</code></pre>

<p><img src="/img/tutorial-images/osmplotr/map1.png" alt="" /></p>

<p>The function <code>print_osm_map</code> creates a graphics device that is scaled to the
bounding box of the map.  Note also that <code>osmplotr</code> maps contain no margins and
fill the entire plot area.  Additional capabilities of <code>osmplotr</code> are described
in the following sections, beginning with downloading and extraction of data.</p>

<h3 id="downloading-data">Downloading Data</h3>

<p>The main function for downloading OSM data from the
<a href="https://overpass-api.de">overpass API</a> is <code>extract_osm_objects</code>. Data of a
particular type can be extracted by passing the appropriate OSM <code>key</code>, as in the
above example:</p>

<pre><code class="language-r">bbox &lt;- get_bbox(c(-0.13, 51.51, -0.11, 51.52))
dat_B &lt;- extract_osm_objects(key = 'building', bbox = bbox)
dat_H &lt;- extract_osm_objects(key = 'highway', bbox = bbox)
</code></pre>

<p>These objects are of appropriate <code>Spatial</code> classes:</p>

<pre><code class="language-r">class(dat_B); class(dat_H)
</code></pre>

<pre><code>#&gt; [1] &quot;sf&quot;         &quot;data.frame&quot;
</code></pre>

<pre><code>#&gt; [1] &quot;sf&quot;         &quot;data.frame&quot;
</code></pre>

<pre><code class="language-r">class(dat_B$geometry); class(dat_H$geometry)
</code></pre>

<pre><code>#&gt; [1] &quot;sfc_POLYGON&quot; &quot;sfc&quot;
</code></pre>

<pre><code>#&gt; [1] &quot;sfc_LINESTRING&quot; &quot;sfc&quot;
</code></pre>

<p><code>Spatial</code> (<a href="https://cran.r-project.org/package=sf"><code>sp</code></a>) objects may be
returned with,</p>

<pre><code class="language-r">dat_B &lt;- extract_osm_objects(key = 'building', bbox = bbox, sf = FALSE)
</code></pre>

<p>otherwise <code>sf</code> is used as the default format.  The Simple Features (<code>sf</code>)
objects with polygons of London buildings and linestrings of highways
respectively contain</p>

<pre><code class="language-r">nrow(dat_B); nrow(dat_H)
</code></pre>

<pre><code>#&gt; [1] 1759
</code></pre>

<pre><code>#&gt; [1] 1133
</code></pre>

<p>&hellip; 1,759 building polygons and 1,133 highway lines.  <code>extract_osm_objects</code> also
accepts <code>key-value</code> pairs which are passed to the
<a href="https://overpass-api.de">overpass API</a> :</p>

<pre><code class="language-r">dat_T &lt;- extract_osm_objects(key = 'natural', value = 'tree', bbox = bbox)
</code></pre>

<p>Trees are located by single coordinates and are thus point objects:</p>

<pre><code class="language-r">class(dat_T$geometry); nrow(dat_T)
</code></pre>

<pre><code>#&gt; [1] &quot;sfc_POINT&quot; &quot;sfc&quot;
</code></pre>

<pre><code>#&gt; [1] 688
</code></pre>

<h3 id="citing">Citing</h3>

<blockquote>
<p>Mark Padgham (2017). osmplotr: Bespoke Images of &lsquo;OpenStreetMap&rsquo;
  Data. R package version 0.3.0.
  <a href="https://CRAN.R-project.org/package=osmplotr">https://CRAN.R-project.org/package=osmplotr</a></p>
</blockquote>

<h3 id="license-and-bugs">License and bugs</h3>

<ul>
<li>License: <a href="http://opensource.org/licenses/MIT">MIT</a></li>
<li>Report bugs at <a href="https://github.com/ropenscilabs/osmplotr/issues?state=open">our GitHub repo for osmplotr</a></li>
</ul>

<p><a href="#top">Back to top</a></p>

                    </article>
                </div>

                </div>
            </div>
        </div>
    </article>


    <div id="footer">
        <div class="container">
            <div class="row start">
                <div class="col-1 col-1-3 top-8">
                    <img src="/img/icon_short_white.svg" />
                </div>

                <div class="col-9 col-offset-2 top-10 bottom-8">
                    <div class="row between">
                        <div class="col-2 col-1-3">
                            <a href="http://github.com/ropensci" target="_blank"><div class="icon icon-github"></div></a>
                            <a href="http://twitter.com/ropensci" target="_blank"><div class="icon icon-twitter"></div></a>
                            <a href="http://vimeo.com/ropensci" target="_blank"><div class="icon icon-vimeo"></div></a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-2 col-1-3 top-8 bottom-8">
                            <ul>
                                <h5 class="bottom-2">Info</h5>
                                <li><a href="/about">Mission</a></li>
                                <li><a href="/about#team">Team</a></li>
                                <li><a href="/about#collaborators">Collaborators</a></li>
                                <li><a href="/careers">Careers</a></li>

                            </ul>
                        </div>

                        <div class="col-2 col-1-3 top-8 bottom-8">
                            <ul>
                                <h5 class="bottom-2">Work</h5>
                                <li><a href="/packages/">Packages</a></li>
                                <li><a href="/blog/">Blog</a></li>
                                <li><a href="/technotes/">Tech Notes</a></li>
                                <li><a href="/tutorials/">Tutorials</a></li>
                                <li><a href="/usecases/">Use Cases</a></li>
                                <li><a href="/resources/">More Resources</a></li>
                            </ul>
                        </div>
                        <div class="col-2 col-1-3 top-8 bottom-8">
                            <ul>
                                <h5 class="bottom-2">Participate</h5>
                                <li><a href="/contact.html">Contact us</a></li>
                                <li><a href="/community/">Community</a></li>
                                <li><a href="http://onboarding.ropensci.org/">Contribute software</a></li>
                                <li><a href="http://unconf17.ropensci.org/">Unconference</a></li>
                                <li><a href="/coc">Code of conduct</a></li>
                                <li><a href="/donate/">Donate</a></li>
                            </ul>
                        </div>
                        <div class="col-4 top-8 bottom-8">
                            <h5 class="bottom-2"></h5>

                            <p>rOpenSci is a fiscally sponsored project of <a href="http://numfocus.org" target="_blank">NumFOCUS</a></p>
                            <a href="http://numfocus.org" target="_blank"><img src="img/numfocus.png"></a>
                            <br>

                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12 top-8 bottom-9 divider">
                    <p class="top-9">Except where otherwise noted, content on this site is licensed under the <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">CC-BY license</a>.
                    </p>
                </div>
            </div>
        </div>
    </div>




    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    

    
    <script type="text/javascript" src="/js/highlight.pack.js"></script>
    <script type="text/javascript">
        hljs.initHighlightingOnLoad();
    </script>



</body>
</html>
