---
logo: "logo_2025.png"
paperwidth: 8in
paperheight: 9in
cardwidth: 4in
cardheight: 3in
cols: 2
rows: 3
mainfont: Helvetica
output: pagedown::business_card
---
```{r include=FALSE, eval=FALSE}
#Update speaker pronouns
#Add blanks
#Check duplicates
#remember combos as well
```
::: {.wrapper data-repeat='1'}
[Andy]{slot='name'}
[&nbsp;]{slot='title'}
[&nbsp;]{slot='email'}
[Workshop]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Lisset]{slot='name'}
[Dumet]{slot='title'}
[she/her/ella]{slot='email'}
[Workshop]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Rosemelly]{slot='name'}
[Jimenez Medal]{slot='title'}
[she/her/ella]{slot='email'}
[Workshop]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Jeffrey]{slot='name'}
[Koss]{slot='title'}
[&nbsp;]{slot='email'}
[Workshop]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Paul]{slot='name'}
[Kunke]{slot='title'}
[&nbsp;]{slot='email'}
[Workshop]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Frances]{slot='name'}
[Lin]{slot='title'}
[she/her]{slot='email'}
[Workshop]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Marty]{slot='name'}
[Marquis]{slot='title'}
[&nbsp;]{slot='email'}
[Workshop]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Albert]{slot='name'}
[Ramon]{slot='title'}
[he/him]{slot='email'}
[Workshop]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Kevin]{slot='name'}
[&nbsp;]{slot='title'}
[&nbsp;]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Michael]{slot='name'}
[&nbsp;]{slot='title'}
[&nbsp;]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Igor]{slot='name'}
[Amelichev]{slot='title'}
[&nbsp;]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Ryan]{slot='name'}
[Ames]{slot='title'}
[he/him]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Tim]{slot='name'}
[Anderson]{slot='title'}
[he/him]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Frank]{slot='name'}
[Aragona]{slot='title'}
[&nbsp;]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Dror]{slot='name'}
[Berel]{slot='title'}
[&nbsp;]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Ed]{slot='name'}
[Borasky]{slot='title'}
[he/him]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Alexa]{slot='name'}
[Bovenkamp]{slot='title'}
[she/her]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Alisha]{slot='name'}
[Bruton]{slot='title'}
[she/her]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Scott]{slot='name'}
[Chamberlain]{slot='title'}
[he/him]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Benjamin]{slot='name'}
[Chan]{slot='title'}
[he/him]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Shiyu]{slot='name'}
[Chen]{slot='title'}
[&nbsp;]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Trevor]{slot='name'}
[Davis]{slot='title'}
[&nbsp;]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Lindsay]{slot='name'}
[Dickey]{slot='title'}
[she/her]{slot='email'}
[Speaker]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Cheryl]{slot='name'}
[Dietrich]{slot='title'}
[she/her]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Kim]{slot='name'}
[Dill-McFarland]{slot='title'}
[she/her]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Diana]{slot='name'}
[Dishman]{slot='title'}
[she/her]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Olivia]{slot='name'}
[Dobbs]{slot='title'}
[she/her]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Robbie]{slot='name'}
[Edwards]{slot='title'}
[he/him]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Daniel]{slot='name'}
[Fish]{slot='title'}
[he/him]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Miranda]{slot='name'}
[Fix]{slot='title'}
[she/her]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Aditya]{slot='name'}
[Gadkari]{slot='title'}
[he/him]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Jon]{slot='name'}
[Garrow]{slot='title'}
[he/him]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Francisco J.]{slot='name'}
[Guerrero]{slot='title'}
[he/him]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Jennifer]{slot='name'}
[Gulley]{slot='title'}
[&nbsp;]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Douglas]{slot='name'}
[Hanes]{slot='title'}
[&nbsp;]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Andie]{slot='name'}
[Hendrick]{slot='title'}
[she/her]{slot='email'}
[Speaker]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Megan]{slot='name'}
[Holtorf]{slot='title'}
[she/her]{slot='email'}
[Speaker]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Kyle]{slot='name'}
[Jones]{slot='title'}
[he/him]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Paulina]{slot='name'}
[Kaiser]{slot='title'}
[she/her]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Zhian]{slot='name'}
[Kamvar]{slot='title'}
[he/him]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Bill]{slot='name'}
[Kayser]{slot='title'}
[&nbsp;]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Charles]{slot='name'}
[Kerr]{slot='title'}
[&nbsp;]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Eric]{slot='name'}
[Kiflawi]{slot='title'}
[&nbsp;]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Sj]{slot='name'}
[Kim]{slot='title'}
[she/they]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Chad]{slot='name'}
[Koehnen]{slot='title'}
[he/him]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Jessica]{slot='name'}
[Kunke]{slot='title'}
[she/they]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Hunter]{slot='name'}
[Ladd]{slot='title'}
[he/him]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Benjamin]{slot='name'}
[Lamp]{slot='title'}
[he/him]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Tammy]{slot='name'}
[Lee]{slot='title'}
[&nbsp;]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Mauro]{slot='name'}
[Lepore]{slot='title'}
[he/him]{slot='email'}
[Speaker]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Mauro]{slot='name'}
[Lepore]{slot='title'}
[&nbsp;]{slot='email'}
[Speaker]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Zachary]{slot='name'}
[Lesher]{slot='title'}
[he/him]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Yan]{slot='name'}
[Liu]{slot='title'}
[she/her]{slot='email'}
[Speaker]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Cedar]{slot='name'}
[Mackaness]{slot='title'}
[he/him]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Trisha]{slot='name'}
[Marsh]{slot='title'}
[she/her]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Allyson]{slot='name'}
[Meyers]{slot='title'}
[she/her]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Evan]{slot='name'}
[Miller]{slot='title'}
[&nbsp;]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Jacob]{slot='name'}
[Miller]{slot='title'}
[&nbsp;]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Morgan]{slot='name'}
[Miller]{slot='title'}
[he/him]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Ranya]{slot='name'}
[Muttaleb]{slot='title'}
[she/her]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Jan]{slot='name'}
[Ng]{slot='title'}
[she/her]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Jan]{slot='name'}
[Ng]{slot='title'}
[&nbsp;]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Arilene]{slot='name'}
[Novak]{slot='title'}
[she/her]{slot='email'}
[Speaker]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Spencer]{slot='name'}
[Nystrom]{slot='title'}
[she/her]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Laxmi]{slot='name'}
[Pallathadka]{slot='title'}
[she/her]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Jeff]{slot='name'}
[Pannell]{slot='title'}
[he/him]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Nathan]{slot='name'}
[Parsons]{slot='title'}
[he/him]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Blanca]{slot='name'}
[Perez]{slot='title'}
[she/her]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Nathaniel]{slot='name'}
[Phillips]{slot='title'}
[he/him]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Madison]{slot='name'}
[Pombo]{slot='title'}
[she/her]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Frances]{slot='name'}
[Ran]{slot='title'}
[&nbsp;]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Heaven Le]{slot='name'}
[Roberts]{slot='title'}
[she/her]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Noe]{slot='name'}
[Rodriguez]{slot='title'}
[&nbsp;]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Seth]{slot='name'}
[Rothbard]{slot='title'}
[&nbsp;]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Kavish]{slot='name'}
[Shah]{slot='title'}
[he/him]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Lindsey]{slot='name'}
[Smith]{slot='title'}
[she/they]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Suzanna]{slot='name'}
[Stephens]{slot='title'}
[she/her]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Rachel]{slot='name'}
[Tavolacci]{slot='title'}
[she/her]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Rachel]{slot='name'}
[Tavolacci]{slot='title'}
[&nbsp;]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Nelly]{slot='name'}
[Tkachman]{slot='title'}
[she/her]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Willa]{slot='name'}
[Van Liew]{slot='title'}
[she/they]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Willa]{slot='name'}
[Van Liew]{slot='title'}
[they/she]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Amelia]{slot='name'}
[Vargas]{slot='title'}
[she/they]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Megan]{slot='name'}
[Waldo]{slot='title'}
[she/her]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Amy]{slot='name'}
[Warnock]{slot='title'}
[she/her]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Camille]{slot='name'}
[Wendlandt]{slot='title'}
[she/her]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Hanna]{slot='name'}
[Winter]{slot='title'}
[she/they]{slot='email'}
[Speaker]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Kara]{slot='name'}
[Woo]{slot='title'}
[she/her]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Liana]{slot='name'}
[Wu]{slot='title'}
[&nbsp;]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Annia]{slot='name'}
[Yoshizumi]{slot='title'}
[she/her]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Chia Hua]{slot='name'}
[Yu]{slot='title'}
[he/him]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Beyza]{slot='name'}
[cengiz]{slot='title'}
[&nbsp;]{slot='email'}
[Workshop & Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[&nbsp;]{slot='name'}
[&nbsp;]{slot='title'}
[&nbsp;]{slot='email'}
[Workshop]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[&nbsp;]{slot='name'}
[&nbsp;]{slot='title'}
[&nbsp;]{slot='email'}
[Workshop]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[&nbsp;]{slot='name'}
[&nbsp;]{slot='title'}
[&nbsp;]{slot='email'}
[Workshop]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[&nbsp;]{slot='name'}
[&nbsp;]{slot='title'}
[&nbsp;]{slot='email'}
[Workshop]{slot='url'}
:::

```{css}
.wrapper {
  color: black;
  background-color: white;
  /*border: 1px dashed grey; /*Only need if cutting out ourselves */
  border: 5px  white;
  text-align: center;
  background-repeat: no-repeat;
  background-position: center center;
  background-size: cover;
  border-bottom: 50px solid #a7e5d8;
  margin-bottom: 10px;
  box-sizing: border-box;
}

[slot="name"] {
  font-weight: normal;
  font-size: 40px;
  margin: 0 0 0 0;
  position: relative;
  top: 2em;
}

[slot="title"] {
  font-weight: normal;
  font-size: 40px;
  margin: 0 0 0 0;
  position: relative;
  top: 2.2em;
}

[slot="email"]  {
  font-weight: normal;
  font-size: 25px;
  color: black;
  margin: 0 0 0 0;
  position: relative;
  top: 3.2em;
}

[slot="url"] {
  font-weight: normal;
  font-size: 25px;
  padding-top: 0em;
  color: black;
  margin: 0 0 0 0;
  position: relative;
  top: 5.5em;
}

.logo {
  height: 7.2%;
  float: left;
  margin-left: 10px;
  margin-top: -10px;
  position: absolute;
}

.page {
  margin: 0in;
}
```

```{r include=FALSE, eval=FALSE}
setwd("~/Documents/GitHub/CascadiaR/pdxrconf.github.io/R_code/name_tags")
pagedown::chrome_print("name_tags_workshop.Rmd")
```
