---
logo: "logo_2025.png"
paperwidth: 8in
paperheight: 9in
cardwidth: 4in
cardheight: 3in
cols: 2
rows: 3
mainfont: Helvetica
output: pagedown::business_card
---
```{r include=FALSE, eval=FALSE}
#Update speaker pronouns
#Add blanks
#Check duplicates
#fix L Borland
```
::: {.wrapper data-repeat='1'}
[Frank]{slot='name'}
[Aragona]{slot='title'}
[&nbsp;]{slot='email'}
[Speaker]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Dror]{slot='name'}
[Berel]{slot='title'}
[&nbsp;]{slot='email'}
[Speaker]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[L]{slot='name'}
[Borland]{slot='title'}
[they/them]{slot='email'}
[Speaker]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Ariane]{slot='name'}
[Erickson]{slot='title'}
[she/her]{slot='email'}
[Speaker]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Peter]{slot='name'}
[Geissert]{slot='title'}
[he/him]{slot='email'}
[Speaker]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[David]{slot='name'}
[Gerbing]{slot='title'}
[&nbsp;]{slot='email'}
[Speaker]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Samer]{slot='name'}
[Hijjazi]{slot='title'}
[he/him]{slot='email'}
[Speaker]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[David]{slot='name'}
[Keyes]{slot='title'}
[he/him]{slot='email'}
[Speaker]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Alec]{slot='name'}
[Kretchun]{slot='title'}
[&nbsp;]{slot='email'}
[Speaker]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Ted]{slot='name'}
[Laderas]{slot='title'}
[he/him]{slot='email'}
[Speaker]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Evan]{slot='name'}
[Landman]{slot='title'}
[he/him]{slot='email'}
[Speaker]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Ben]{slot='name'}
[Matheson]{slot='title'}
[he/him]{slot='email'}
[Speaker]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Jonathan]{slot='name'}
[McPherson]{slot='title'}
[he/him]{slot='email'}
[Speaker]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Josiah]{slot='name'}
[Parry]{slot='title'}
[he/him]{slot='email'}
[Speaker]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Carrie]{slot='name'}
[Preston]{slot='title'}
[she/her/they/them]{slot='email'}
[Speaker]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Charlotte]{slot='name'}
[Wickham]{slot='title'}
[she/her]{slot='email'}
[Speaker]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Faycal]{slot='name'}
[ounacer]{slot='title'}
[he/him]{slot='email'}
[Speaker]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[David]{slot='name'}
[Alsalemi]{slot='title'}
[&nbsp;]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Max]{slot='name'}
[Arensberg]{slot='title'}
[they/he]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Erica]{slot='name'}
[Bishop]{slot='title'}
[she/her]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Rafid]{slot='name'}
[Chowdhury]{slot='title'}
[he/him]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Annicca]{slot='name'}
[Christine]{slot='title'}
[she/her]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Madison]{slot='name'}
[Cox]{slot='title'}
[she/her]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Erin]{slot='name'}
[Dahl]{slot='title'}
[&nbsp;]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Katherine]{slot='name'}
[Do]{slot='title'}
[&nbsp;]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Robyn]{slot='name'}
[Dove]{slot='title'}
[she/her]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Vania]{slot='name'}
[Fong]{slot='title'}
[&nbsp;]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Oluwaseun]{slot='name'}
[Fowotade]{slot='title'}
[he/him]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Duncan]{slot='name'}
[Gates]{slot='title'}
[&nbsp;]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Joshua]{slot='name'}
[Golconda]{slot='title'}
[he/him]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Ethan]{slot='name'}
[Greenidge]{slot='title'}
[he/they]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Erica]{slot='name'}
[Hernandez]{slot='title'}
[she/they]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Kristen]{slot='name'}
[Hollywood]{slot='title'}
[&nbsp;]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Regan]{slot='name'}
[Hutson]{slot='title'}
[he/him]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Rosemelly]{slot='name'}
[Jimemez Medal]{slot='title'}
[she/her/ella]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Joella]{slot='name'}
[Jinno]{slot='title'}
[she/they]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Andy]{slot='name'}
[Kaempf]{slot='title'}
[&nbsp;]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Emily]{slot='name'}
[Katzton]{slot='title'}
[she/her]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Cody]{slot='name'}
[Kerr]{slot='title'}
[&nbsp;]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Charles]{slot='name'}
[King]{slot='title'}
[he/him]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Joseph]{slot='name'}
[Korpela]{slot='title'}
[he/him]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Mike]{slot='name'}
[LeVan]{slot='title'}
[he/him]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Pierrette]{slot='name'}
[Lo]{slot='title'}
[she/her]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Patrick]{slot='name'}
[Lyons]{slot='title'}
[he/him]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Marty]{slot='name'}
[MARQUIS]{slot='title'}
[he/him]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Darian]{slot='name'}
[Madere]{slot='title'}
[&nbsp;]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Kathy]{slot='name'}
[Matos Linares]{slot='title'}
[she/her]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Ian]{slot='name'}
[McDonald]{slot='title'}
[he/him]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Ann]{slot='name'}
[McMonigal]{slot='title'}
[she/her]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Jennifer]{slot='name'}
[Meneghin]{slot='title'}
[she/her]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Kathleen]{slot='name'}
[Moore]{slot='title'}
[she/her]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Blazej]{slot='name'}
[Neradilek]{slot='title'}
[he/him]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Thaibinhduong]{slot='name'}
[Nguyen]{slot='title'}
[she/her]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Andey]{slot='name'}
[Nunes-Brewster]{slot='title'}
[&nbsp;]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Charles]{slot='name'}
[Parker]{slot='title'}
[&nbsp;]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Anamaria]{slot='name'}
[Perez]{slot='title'}
[&nbsp;]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Francesca]{slot='name'}
[Pieraccini]{slot='title'}
[&nbsp;]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Ann]{slot='name'}
[Rasmussen]{slot='title'}
[she/her]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Nori]{slot='name'}
[Redmond]{slot='title'}
[&nbsp;]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Alexandria]{slot='name'}
[Reed]{slot='title'}
[she/her]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Maya]{slot='name'}
[Rios]{slot='title'}
[she/her]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Katie]{slot='name'}
[Russell]{slot='title'}
[she/her]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Tige]{slot='name'}
[Rustad]{slot='title'}
[&nbsp;]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Bryan]{slot='name'}
[Shalloway]{slot='title'}
[&nbsp;]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Emily]{slot='name'}
[Silver]{slot='title'}
[&nbsp;]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Matthew]{slot='name'}
[Slaughter]{slot='title'}
[&nbsp;]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Vivek]{slot='name'}
[Sriram]{slot='title'}
[he/him]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Elyse]{slot='name'}
[St Sauver]{slot='title'}
[she/her]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Henry]{slot='name'}
[Ugorji]{slot='title'}
[&nbsp;]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Aparna]{slot='name'}
[Upadhyay]{slot='title'}
[she/her]{slot='email'}
[Conference]{slot='url'}
:::
::: {.wrapper data-repeat='1'}
[Xinyao]{slot='name'}
[deGrauw]{slot='title'}
[&nbsp;]{slot='email'}
[Conference]{slot='url'}
:::
```{css}
.wrapper {
  color: black;
  background-color: white;
  /*border: 1px dashed grey; /*Only need if cutting out ourselves */
  border: 5px  white;
  text-align: center;
  background-repeat: no-repeat;
  background-position: center center;
  background-size: cover;
  border-bottom: 50px solid #25abb8;
  margin-bottom: 10px;
  box-sizing: border-box;
}

[slot="name"] {
  font-weight: normal;
  font-size: 40px;
  margin: 0 0 0 0;
  position: relative;
  top: 2em;
}

[slot="title"] {
  font-weight: normal;
  font-size: 40px;
  margin: 0 0 0 0;
  position: relative;
  top: 2.2em;
}

[slot="email"]  {
  font-weight: normal;
  font-size: 25px;
  color: black;
  margin: 0 0 0 0;
  position: relative;
  top: 3.2em;
}

[slot="url"] {
  font-weight: normal;
  font-size: 25px;
  padding-top: 0em;
  color: black;
  margin: 0 0 0 0;
  position: relative;
  top: 5.5em;
}

.logo {
  height: 7.2%;
  float: left;
  margin-left: 10px;
  margin-top: -10px;
  position: absolute;
}

.page {
  margin: 0in;
}
```

```{r include=FALSE, eval=FALSE}
setwd("~/Documents/GitHub/CascadiaR/pdxrconf.github.io/R_code/name_tags")
pagedown::chrome_print("name_tags_conf.Rmd")
```
