---
logo: "logo_2025.png"
paperwidth: 8in
paperheight: 9in
cardwidth: 4in
cardheight: 3in
cols: 2
rows: 3
mainfont: Helvetica
output: pagedown::business_card
---

```{r eval=FALSE, include=FALSE}
# HOW TO
# 1. Update the logo file in the header and make sure that file is in the same directory as this Rmd file
# 2. Paste in the output from name_tag_data_prep.R below this code chunk. Remove the example below
#     - All tickets in each Rmd get the same banner color so recommend separate files for organizer, conf, and workshops
# 3. Proofread for repeats or errors that made it through the Rscript
# 4. Add blanks at the end for day-of registrants and name tag errors
#     - Blanks just have a space character code in all the [ ] aka &nbsp;
# 5. Update the wd and file name at the end.
# 6. Knit!

# OPTIONAL
# 1. Change the log size with logo height: 10%; Make sure it doesn't overlap the longest first name you have
# 2. Change the bottom banner color in the wrapper border-bottom: 50px solid #e59a91; Suggest using opposing color for a committee "highlight" such as red vs green, blue vs orange, etc

```

::: {.wrapper data-repeat='1'}
[FIRST]{slot='name'}
[LAST]{slot='title'}
[PRONOUNS]{slot='email'}
[TICKET TYPE]{slot='url'}
:::

```{css}
.wrapper {
  color: black;
  background-color: white;
  /*border: 1px dashed grey; /*Only need if cutting out ourselves */
  border: 5px  white;
  text-align: center;
  background-repeat: no-repeat;
  background-position: center center;
  background-size: cover;
  border-bottom: 50px solid #e59a91;
  margin-bottom: 10px;
  box-sizing: border-box;
}

[slot="name"] {
  font-weight: normal;
  font-size: 40px;
  margin: 0 0 0 0;
  position: relative;
  top: 2em;
}

[slot="title"] {
  font-weight: normal;
  font-size: 40px;
  margin: 0 0 0 0;
  position: relative;
  top: 2.2em;
}

[slot="email"]  {
  font-weight: normal;
  font-size: 25px;
  color: black;
  margin: 0 0 0 0;
  position: relative;
  top: 3.2em;
}

[slot="url"] {
  font-weight: normal;
  font-size: 25px;
  padding-top: 0em;
  color: black;
  margin: 0 0 0 0;
  position: relative;
  top: 5.5em;
}

.logo {
  height: 10%;
  float: left;
  margin-left: 10px;
  margin-top: -10px;
  position: absolute;
}

.page {
  margin: 0in;
}
```

```{r include=FALSE, eval=FALSE}
setwd("YOUR_DIRECTORY")
pagedown::chrome_print("name_tags_GROUP.Rmd")
```
